### ISSUE TITLE
Implement remaining features to Circuit prototype

### ISSUE THREAD

**Issue by MaciejBaj** [t3rn/t3rn#33]
### Description
implement a Circuit that implements all of the protocol features outlined in the whitepaper except any network-related ones, therefore still works as on semi-decentralised PoA premises. Authorities validate the execution via multiple integrated gateways and produce publicly verifiable proofs of that execution.

### Acceptance Criteria

- [ ] Authorities guarantee the execution correctness by re-validating the execution and producing verifiable proofs.
- [ ] Implement a transaction pool for execution requests and order the requests by execution fees.
- [ ] Implement fishermen dispatching proofs of misbehaviour and execute on them by ensuring the execution of x2 transactions worth.
- [ ] Expose API and register new gateways and blockchains dynamically. Work out and implement a pricing model for running active gateways and contracts on Circuit (note that as collecting witness from a gateway grows the witness collider size).
- [ ] Form multi-signature for the support of transaction-only external gateway based on fast Multiparty Threshold ECDSA.
