### ISSUE TITLE
Implement Proof of Stake Circuit

### ISSUE THREAD

**Issue by MaciejBaj** [t3rn/t3rn#35]
### Description

Implement a Circuit that works on decentralised Proof of Stake premises and demonstrates it on Testnet with the participation of independent community members taking active roles of validators/execution agents.

### Acceptance Criteria

- [ ] Register validators upon receiving their bonding stake and implement their bonded stake slashing.
- [ ] Implement Golden Ticket selection of the next execution agent using BABE algorithm. 	
- [ ] Support on-chain voting for validators and implement it as part of the selection algorithm.
- [ ] Implement staking in foreign currencies and seamless exchange between them during interoperable execution.
- [ ] [Bonus] Implement necessary features for block collators as preparation for a Parachain slot.
