### ISSUE TITLE
Upgrade Gateways Pallets to FRAMEv2 - Subtask #31

### ISSUE THREAD

**Issue by MaciejBaj** [t3rn/t3rn#66]
### Description

Upgrade all Gateways-relevant pallets and runtimes to FRAMEv2

### Acceptance Criteria

- [x] pallet-runtime-gateway sources
- [x] pallet-runtime-gateway tests 
~~- [ ] pallet-contracts-gateway sources~~
~~- [ ] pallet-contracts-gateway tests~~
- [x] demo: pallet-flipper
- [x] demo: pallet-weights
- [x] demo-runtime

**Comment by MaciejBaj** [comment]
Closed by #56

**Comment by MaciejBaj** [comment]
Subtask of #31
