### ISSUE TITLE
Testing: SFX creation framework

### ISSUE THREAD

**Issue by petscheit** [t3rn/t3rn#711]
### Item Type

Epic

### Description
Currently, we can generate SFX data with the cli. This is already useful for checking the happy paths through the circuit. However, we also want to be able to test the unhappy paths, to ensure we fail where we should. This is a bit more tricky to generate, as the failure comes from external actors (mostly executors). We can achieve this by using certain parameters of an SFX to allow clients to identify at which point a transaction should fail. 

The path of least resistance is to wrap this functionality around the CLI, which will then be used to submit and generate the data we want. 

### Error Modes:
- NoBidders: No executor should bid on this SFX
- ConfirmationTimout: The executor never submits a confirmation
- InvalidProof: The submitted inclusion proof is invalid
- InvalidExecutionValidProof: The executor sends the wrong amount, but submits valid proof for the TX

### Tasks:
- [x] Tie the different error modes to a specific parameter of the SideEffect that we don't use too much. I would recommend the signature field, as its used nowhere currently
- [x] Create a TS function that allows the creation of the different SFX types, along with the error mode. This should internally call CLI with the required params. CLI will then export if setup correctly

### Acceptance Criteria

- We can programmatically create all the different SFX types, while injecting an identifier for the error mode into the signature

### What are the points assigned to this item?

None

### Is the issue ready?

- [X] This issue is ready
